// Program4: Case Class
case class Car(name: String, model: String) {

  val carName = name
  val carModel = model

  def printDetails(): Unit = {

    println(s"Car Name is: ${carName} and Car Model is: ${carModel}")
  
  }

}


object CaseClassDemoA {

  def main(args: Array[String]): Unit = {

    val bmw = Car(name="BMW", model="550")  // no need to write "new" since apply method is autogenerated
    bmw.printDetails()

    bmw match {case Car(a, b) => println(a, b)}  // There is unapply method used for matching

    // Autogenerates copy method
    val mercedes = bmw.copy(name="mercedes")  // it copies the bmw instance and changes the name only!
    mercedes.printDetails()

    // equals and hashcode methods
    println(bmw == mercedes)

    // toString method is autoimplemented
    println(bmw)  // It does not work in a standard class (you get object ID)
  }
}
